name: test autocore_build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      namapaket:
        description: "namapaket"
        required: false
        default: "autocore-x86"
        type: choice
        options:
          - luci-app-tinyfilemanager
          - luci-app-netmonitor
          - luci-app-adguardhome
          - luci-theme-argon
          - luci-app-argon-config
          - autocore
          - autocore-x86
          - autocore-arm
          
jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 23.05.3
         # - snapshot
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

#      - name: Free disk space
#        run: |
#          sudo rm -rf /usr/lib/{jvm,llvm} /usr/local /usr/src/* /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm} /usr/libexec/gcc/x86_64-linux-gnu/14 /usr/lib/x86_64-linux-gnu/{*clang*,*LLVM*} /home/linuxbrew
          
      - name: Get v2ray-geodata
        run: |
          git clone --depth 1 --branch main https://github.com/asvow/luci-app-tailscale.git luci-app-tailscale
          git clone https://github.com/sbwml/luci-theme-argon
          git clone --depth 1 --branch master https://github.com/gSpotx2f/luci-app-internet-detector
          git clone --depth 1 --branch main https://github.com/zero2black/luci-app-tinyfilemanager
        
          
      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
         # PACKAGES: ${{ github.event.inputs.namapaket }}
         # PACKAGES: luci-app-argon-config luci-app-tailscale luci-app-internet-detector
          PACKAGES: luci-app-tinyfilemanager
          NO_REFRESH_CHECK: true
         
      - name: Store packages
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tag }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      
      - name: Prepare for Push
        run: |
          mkdir -p x86_v23
          cp bin/packages/${{ matrix.arch }}/packages_ci/*.ipk x86_v23/
          
      - name: Push Artifacts to paket_o Repository
        run: |
          git clone https://github.com/${{ github.repository_owner }}/paket_o target_repo
          cd target_repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B x86_v23
          cp -r ../x86_v23/* .
          git add .
          git commit -m "Update autocore .ipk packages for ${{ matrix.arch }}"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/paket_o.git x86_v23 --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 0

