name: Build lucitz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev pkg-config zlib1g-dev gawk git ccache gettext libssl-dev libxml2-dev xsltproc wget unzip python3 zstd

    - name: Get latest python-telegram-bot version
      run: |
        LATEST_VERSION=$(pip index versions python-telegram-bot | grep -oP '(?<=python-telegram-bot )[\d.]+(?=\s)' | head -n 1)
        echo "PYTHON_TELEGRAM_BOT_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Setup Environment Variables
      run: |
        export TZ=Asia/Jakarta
        echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz > /dev/null
        tar xf openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz > /dev/null
        mv openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64 openwrt-sdk > /dev/null

    - name: Update and install feeds
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a > /dev/null
        ./scripts/feeds install -a > /dev/null

    - name: Configure build
      run: |
        cd openwrt-sdk
        make defconfig

        # echo "CONFIG_ALL_NONSHARED=n" > .config
        # echo "CONFIG_ALL_KMODS=n" >> .config
        # echo "CONFIG_ALL=n" >> .config
        # echo "CONFIG_AUTOREMOVE=n" >> .config
        # echo "CONFIG_LUCI_LANG_zh_Hans=n" >> .config
        echo "CONFIG_PACKAGE_python3-packages=y" >> .config
        echo 'CONFIG_PACKAGE_python3-packages-list="python-telegram-bot"' >> .config

    - name: Compile python-dotmap
      run: |
        cd openwrt-sdk
        ls
        make package/feeds/packages/python3-packages/compile  V=s -j10

    - name: Rename IPK package
      run: |
        cd openwrt-sdk/bin/packages/x86_64/packages
        mv python3-packages_1.0-2_x86_64.ipk python-telegram-bot_${{ env.PYTHON_TELEGRAM_BOT_VERSION }}_x86_64.ipk

    - name: List compiled files
      run: |
        cd openwrt-sdk
        find bin -name "*.ipk"

    - name: Upload IPK package
      uses: actions/upload-artifact@v4
      with:
        name: luci-theme-argon
        path: |
          openwrt-sdk/bin/packages/x86_64/packages/python-telegram-bot_${{ env.PYTHON_TELEGRAM_BOT_VERSION }}_x86_64.ipk

    - name: Zip packages
      run: |
        echo -e "testing" >> release.txt

    - name: Upload packages
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        artifacts: |
            openwrt-sdk/bin/packages/**/python-telegram-bot_${{ env.PYTHON_TELEGRAM_BOT_VERSION }}_x86_64.ipk
        allowUpdates: true
        replacesArtifacts: true
        bodyFile: "release.txt"
        tag: x86_ipk
